version: '3'
services:
  app:
    container_name: pet-finder-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "9090:80"
    restart: always
    command: sh -c "npm run dev -- --host"
